### ISSUE TITLE
Scalable

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/katelibby#256]
The goal of this ticket is simple, make the bot Scalable, must be able to run more than one instance. 
There are a few things which need to be done to achieve this. 
* [x] - Containerization of Application https://github.com/wh-iterabb-it/katelibby/issues/249
* [ ] - Status and Load Checks https://github.com/wh-iterabb-it/katelibby/issues/254
* [ ] - Load balance connections and event listeners https://github.com/wh-iterabb-it/katelibby/issues/255
* [x] - Multiple instances running at same time

**Comment by BeauBouchard** [comment]
i think a hosting service like heroku or allowing the Slack button integration #246 will solve this
